name: DUCO CLI Miner

on:
  workflow_dispatch:

jobs:
  cli-mine:
    runs-on: ubuntu-latest
    timeout-minutes: 360  # Giới hạn GitHub Actions

    steps:
    - name: Clone repo
      run: git clone https://github.com/nam2010-pp/minercli.git miner

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install CLI-only dependencies
      run: |
        cd miner
        npm install benchmark@2.1.4
        npm install ini@3.0.0
        npm install js-sha1@0.6.0
        npm install jshashes@1.0.8
        npm install node-fetch@2.6.1
        npm install promise-socket@6.0.3
        npm install rusha@0.8.14
        npm install sha1@1.1.1

    - name: Run DUCO CLI miner
      run: |
        cd miner
        node cli.js

    - name: 🔁 Re-trigger after 6h to continue mining
      if: always()
      run: |
        echo "Triggering re-run after 6h..."
        curl -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.GH_PAT }}" \
          https://api.github.com/repos/${{ github.repository }}/actions/workflows/${{ github.workflow }}/dispatches \
          -d '{"ref":"main"}'
