name: DUCO CLI Miner

on:
  workflow_dispatch:

jobs:
  cli-mine:
    runs-on: ubuntu-latest
    timeout-minutes: 360

    steps:
    - name: Clone repo
      run: git clone https://github.com/nam2010-pp/minercli.git miner

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install CLI-only dependencies
      run: |
        cd miner
        npm init -y
        npm install benchmark@2.1.4 ini@3.0.0 js-sha1@0.6.0 jshashes@1.0.8 \
                    node-fetch@2.6.1 promise-socket@6.0.3 rusha@0.8.14 sha1@1.1.1

    - name: Run DUCO CLI miner
      run: |
        cd miner
        node cli.js
